### ISSUE TITLE
does this include centermask?

### ISSUE THREAD

**Issue by jinfagang** [youngwanLEE/vovnet-detectron2#1]
fcos head and centermask included?

**Comment by stigma0617** [comment]
@jinfagang 
Not yet. 
So far only VoVNetV2 backbone networks.
I'm supposed to update centermask in detectron2 version.

**Comment by youngwanLEE** [comment]
@jinfagang 
Not yet.

So far VoVNet backbones are available in detectron2.

I'm supposed to upload the CenterMask in detectron2.

**Comment by youngwanLEE** [comment]
@jinfagang

we now open the [centermask2](https://github.com/youngwanLEE/centermask2).
