### ISSUE TITLE
AttributeError: Attempted to set WEIGHTS to /checkpoints/FRCN-V2-39-3x/model_final.pth, but CfgNode is immutable

### ISSUE THREAD

**Issue by Samjith888** [youngwanLEE/vovnet-detectron2#4]
While evaluation , getting the following error

AttributeError: Attempted to set WEIGHTS to /checkpoints/FRCN-V2-39-3x/model_final.pth, but CfgNode is immutable

**Comment by jGsch** [comment]
After `cfg.freeze()`, if you want modfiy `cfg`, we have to `cfg.defrost()`
