### ISSUE TITLE
backbone weights pretrained on ImageNet-1k dataset

### ISSUE THREAD

**Issue by bochenghu** [youngwanLEE/vovnet-detectron2#5]
Hi Youngwan,
I really love your project, but the ImageNet pretrained weights are on Dropbox which are inaccessible for me, would you mind put them on Google Drive, thank you very much!

**Comment by youngwanLEE** [comment]
@bochenghu 
Hi,
I don't have enough google storage to put the weights.

Could you let me know which file you can't download?

By the way,
when you train with vovnet-configs, the pretrained weight will be downloaded automatically.

**Comment by bochenghu** [comment]
Hi Youngwan,
I've already obtained all of the ImageNet pretrained weights with the help of my friend, now I can run the code properly, thank you all the same.
