### ISSUE TITLE
Used pretrained model mask_rcnn_V_99_FPN_3x on custom dataset  

### ISSUE THREAD

**Issue by DINOUS11** [youngwanLEE/vovnet-detectron2#9]
I got this error while training with custom dataset

RuntimeError: The size of tensor a (81) must match the size of tensor b (6) at non-singleton dimension 0
![image](https://user-images.githubusercontent.com/62002655/78242888-c6eacf00-751d-11ea-9a05-691ee7d4cd04.png)

**Comment by youngwanLEE** [comment]
@DINOUS11 
My checkpoint includes an optimizer that was used in the training step on COCO.

I recommend 

1. load the checkpoint
2. remove the optimizer key and values or save the only model in the new file.

**Comment by DINOUS11** [comment]
@youngwanLEE  how can i save the only model in new file, thanks so much :+1:

**Comment by youngwanLEE** [comment]
Briefly,
```
checkpoint_path = "path/to/the/mask_V_99_eSE_ms_3x.pth"
new_path = ''path/to/the/mask_V_99_eSE_ms_3x.pth"

checkpoint = torch.load(checkpoint_path)

new_model_state_dict = {}
for k, v in checkpoint.items():
    if "model" in k:
        new_model_state_dict[k] = v

torch.save(new_model_state_dict, new_path)
```

**Comment by DINOUS11** [comment]
@youngwanLEE it runs perfectly now, very appreciate for your work :100: 
![image](https://user-images.githubusercontent.com/62002655/78315814-0dc9da80-7599-11ea-93e8-96e942440c87.png)

**Comment by DINOUS11** [comment]
@youngwanLEE  after training i load checkpoint to eval but this keeps happening
![image](https://user-images.githubusercontent.com/62002655/78336656-b3497200-75ca-11ea-88bc-deb7fd343d09.png)

This was the code
![image](https://user-images.githubusercontent.com/62002655/78336768-e4c23d80-75ca-11ea-82db-64321298ba97.png)
